cqfn/degitx

white-paper/wp.tex

#1 - added cooperation section and todos for other solutions: Spokes, Gitaly, JGit, IPFS, brig.

Compare with other solutions

---

white-paper/wp.tex

#1 - added design draft to solution section: description of possible workflow and main protocol components.

Design draft

---

API_GITALY.md

#2 - Gitaly gRPC API & Implementation description (without Ruby-based RPC impls)

Gitaly RPC description

---

.github/workflows/ci.yaml
.gitignore
cmd/node/main.go
degitx.go
degitx_test.go
go.mod
go.sum

#4 - added app `main` package skeleton with `degitx` package with tests and CI.

App skeleton with tests and ci

---

GRPC_CALL_WORKFLOW.md

#2 - described gRPC call workflow

---

API_GITALY.md
GRPC_CALL_WORKFLOW.md

#2 - typos fixed

---

white-paper/wp.tex

Locators explained

---

README.md

Added loc badge

---

.github/workflows/ci.yaml
Makefile
README.md
proto/Makefile
proto/go/degitxpb/PACKAGE_DESCRIPTION.md

#4 - added `Makefile`s for build, test and proto files, updated readme.

Added makefiles

---

.github/workflows/wp-lint.yml

#1 - added hite-paper build job on pull requests

White paper build on pull requests

---

white-paper/wp.tex

#3 - add git file storage details

add git file storage details

---

README.md

#27 code review:
added node config description in readme

#27 - node config described

---

README.md
white-paper/wp.tex

#25 - added references to white paper

Added wp references

---

Makefile
cmd/node/config.go
cmd/node/config_test.go
cmd/node/main.go
locators/locator.go
locators/locator_test.go

#44 - extracted locators logic to new package to reuse it for discovery protocol implementation

Locators extracted

---

cmd/node/config.go
cmd/node/config_test.go
cmd/node/main.go
degitx.go
discovery/client.go
discovery/discovery.go
discovery/discovery_test.go
discovery/net.go
discovery/net_test.go
discovery/peers.go
discovery/peers_test.go
discovery/server.go
go.mod
go.sum
locators/locator.go
locators/locator_test.go
misc/utils.go

#53 - implemented discovery client, tested locally, fixed gRPC issues, refactored common code

Discovery client implementation

---

.golangci.yml

#19 - added linter for license checks

#19 - linter for license checks

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

#66 - Added CONTRIBUTING.md file, issues and pull request templates, updated
README.md

Contributing guide

---

white-paper/wp.tex

#70 - replaced squares with UML component diagram in overview diagram.

Overview UML diagram

---

README.md

Thanks for your contribution!
Please read this contributing guide before submitting a pull request:
https://github.com/cqfb/degitx/blob/master/CONTRIBUTING.md#task-solving
If some of contributing requirements will not be met,
the PR could be rejected without explanation.

Update README.md 🚀

---

.github/ISSUE_TEMPLATE.md

Closes #83 - fixed link for issue template

Fixed issue template link

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

#83 - all `cqfb` in links replaced with `cqfn`

#83 - links restored

---

white-paper/explanation.tex
white-paper/wp.tex

#70 - explained how GitLab pushes new changes to DeGitX Gitaly front-end

GitLab with DeGitX push explained

---

white-paper/wp.tex

#62 - lpd described

---

white-paper/explanation.tex
white-paper/wp.tex

#80 - push pack from front-end to back-end and leader election

Push pack from front-end to back-end

---

white-paper/wp.tex

#99 - explained load balancing on front-end nodes to back-ends

Explained load balancing

---

discovery/discovery_test.go
discovery/meta_provider.go
discovery/meta_provider_test.go
discovery/peers.go
discovery/peers_test.go
locators/locator.go
meta/meta.go

#105 - implemented discovery provider over metadata interface

Discovery provider over metadata

---

white-paper/explanation.tex

Removed diagram with push explanation

---

white-paper/wp.tex

#124 - explained how new node can register itself in a system

Explained discovery registration

---

.github/workflows/wp-upload.yml

#130 - upload white-paper pdf to temporary action assets on build

Upload pdf to temporary action assets

---

meta/etcd.go
meta/meta.go

Closes #106 - made all etcd `Storage` operations asynchronous,
passing channel of response to functions and closing channels on
complete.

etcd async ops

---

.0pdd.yml
internal/transaction/hook.go
internal/transaction/manager.go
internal/transaction/meta.go
internal/transaction/paxos.go
internal/transaction/rm.go

For #154 - Added interfaces for reference-transaction hook, transaction manager,
resource manager, Paxos primitives (proposer and acceptors).

Added transaction package, base types and interfaces

---

white-paper/wp.tex

#154 - Explained the transaction details, explained the flow
Added call diagrams and sequence diagram

White-paper updates for atomic transaction

---

reports/3pc-consistency/.gitignore
reports/3pc-consistency/3pc-consistency.tex
reports/3pc-consistency/Makefile

For #162 - started report tex sources:
- Added abstract
- Described the problem
- Started solution section
- Added todos for later
See [PDF](https://github.com/cqfn/degitx/files/6076102/3pc-consistency.pdf).

3PC evaluation report skeleton

---

reports/gitlab-commit-protocol/gitlab-commit-protocol.tex

For https://github.com/cqfn/degitx/issues/179 - Added an intro and Gitaly commit protocol information.

Gitlab protocol report: introduction and 3PC info

---

docs/API_GITALY.md

For https://github.com/cqfn/degitx/issues/185.
Updated the table with gitaly RPC methods. 
Added the table with related issues of implementing go/ruby RPCs.

Updated gitaly RPCs implementation info

---

.github/workflows/ci.yaml
.github/workflows/wp-lint.yml
.gitignore
.golangci.yml
Makefile
README.md
go.mod

Closes #196 - fixed linter workflow by adding missing deps,
updated golanci version, fixed workflow paths.

Fixed github workflows

---

reports/gitlab-commit-protocol/gitlab-commit-protocol.tex

For #179 - added GitLab workflow diagrams for push and
described steps and components.

GitLab push workflow diagram

---

reports/gitlab-commit-protocol/gitlab-commit-protocol.tex

For: https://github.com/cqfn/degitx/issues/179
Added info about repository generations and related problems to report.

Gitlab commit protocol:  generations and related problems

---

wiki/API_GITALY.md

For: https://github.com/cqfn/degitx/issues/185. Updated RPCs test coverage info

Gitaty RPCs info: updated test coverage

---

go.mod
go.sum

Manual update of multiaddr. For https://github.com/cqfn/degitx/pull/212.

Manual update of multiaddr

---

reports/gitlab-commit-protocol/gitlab-commit-protocol.tex

For cqfn#210 and cqfn#179
Complex document refactoring: added intro, virtual storage info, structure refactoring and so on

179 gitaly report finalizer

---

reports/gitlab-commit-protocol/gitlab-commit-protocol.tex

For https://github.com/cqfn/degitx/issues/179.
Added info about Praefect crashing before generation incrementing scenario.

Praefect failure scenario

---

.github/workflows/ci.yaml
Makefile
pkg/paxos/pcommit.go
pkg/paxos/tm_multiplexer.go
pkg/tcommit/manager.go
pkg/tcommit/resource.go
pkg/tcommit/tcommit.go
pkg/tcommit/vote_string.go
pkg/twopc/tmnode.go
pkg/twopc/tmnode_test.go

Removed transaction ID from TM API,
Added optional `Meta` string to pass additional metadata,
Created alias for `Votes`.
Ticket: #177

break! changed transaction commit interfaces
